// examples/browser-vue/src/ListItem.vue
<template>
    <li class="list-group-item">
        <span
            v-for="(chunk, i) in hit.chunks"
            v-bind:key="i"
            v-bind:class="{'font-weight-bold': chunk.highlight}"
        >{{chunk.text}}</span>
    </li>
</template>


<script>
export default {
    name: "list-item",
    props: ["hit"],
}
</script>

// examples/browser-react-ts/src/ListItem.tsx
import {Hit} from 'lucid-suggest/en'
import React from 'react'

type ListItemProps = {
    hit: Hit,
}

const ListItem: React.FC<ListItemProps> = ({hit}) => (
    <li className="list-group-item">
        {hit.chunks.map((chunk, i) => (
            chunk.highlight
                ? <strong key={i}>{chunk.text}</strong>
                : <span key={i}>{chunk.text}</span>
        ))}
    </li>
)

export default ListItem
